---
title: "Octopuse survey results"
author: "Andrew Mertens"
date: "2025-07-12"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

rm(list=ls())
library(tidyverse)
library(here)
library(table1)

d <- readRDS(here("data", "cleaned_octopus_farming_data.RDS"))
colnames(d)
dput(colnames(d))
```


## Explore demographics by country

```{r}
table1(~ Gender + Age + dAGE + URBANRURAL + INCOME | COUNTRY, data=d, transpose=TRUE)
```




## Explore opinions by country

```{r}
table1(~ Q1_awareness + Q2_support + Q4_welfare_knowledge + Q4_environmental_knowledge + Q4_economic_knowledge + 
         Q4_sentience_knowledge + Q4_public_health_knowledge + Q5_consumption_frequency + Q6_impact_on_consumption + 
         Q7_ban_farming_support + Q7_ban_sale_support + Q7_ban_subsidies_support + Q9_vote_candidate_support| COUNTRY, data=d, transpose=FALSE)
```



## Explore demographics by message

```{r}
table1(~ Gender + Age + dAGE + URBANRURAL + INCOME | message, data=d, transpose=FALSE)
```

## Explore opinions by message

```{r}
table1(~ Q1_awareness + Q2_support + Q4_welfare_knowledge + Q4_environmental_knowledge + Q4_economic_knowledge + 
         Q4_sentience_knowledge + Q4_public_health_knowledge + Q5_consumption_frequency + Q6_impact_on_consumption + 
         Q7_ban_farming_support + Q7_ban_sale_support + Q7_ban_subsidies_support + Q9_vote_candidate_support| message, data=d, transpose=FALSE)
```

## Explore opinions by message - coded as continious

```{r}

d[d=="Don't know"] <- NA

d <- d %>%
  mutate(Q1_awareness=as.numeric(Q1_awareness),
         Q2_support=as.numeric(Q2_support),
         Q4_welfare_knowledge=as.numeric(Q4_welfare_knowledge),
         Q4_environmental_knowledge=as.numeric(Q4_environmental_knowledge),
         Q4_economic_knowledge=as.numeric(Q4_economic_knowledge),
         Q4_sentience_knowledge=as.numeric(Q4_sentience_knowledge),
         Q4_public_health_knowledge=as.numeric(Q4_public_health_knowledge),
         Q5_consumption_frequency=as.numeric(Q5_consumption_frequency),
         Q6_impact_on_consumption=as.numeric(Q6_impact_on_consumption),
         Q7_ban_farming_support=as.numeric(Q7_ban_farming_support),
         Q7_ban_sale_support=as.numeric(Q7_ban_sale_support),
         Q7_ban_subsidies_support=as.numeric(Q7_ban_subsidies_support),
         Q9_vote_candidate_support=as.numeric(Q9_vote_candidate_support))
table1(~ Q1_awareness + Q2_support + Q4_welfare_knowledge + Q4_environmental_knowledge + Q4_economic_knowledge + 
         Q4_sentience_knowledge + Q4_public_health_knowledge + Q5_consumption_frequency + Q6_impact_on_consumption + 
         Q7_ban_farming_support + Q7_ban_sale_support + Q7_ban_subsidies_support + Q9_vote_candidate_support| message, data=d, transpose=FALSE)
```

